# Site settings
title: Ginger & Beard
email: your-email@domain.com
description: "Official site of Ginger & Beard."
baseurl: "/ginger-and-beard"
url: "http://yourdomain.com"
twitter_username: jeffrlaw
github_username:  jeffrlaw

# Build settings
markdown: kramdown
permalink: pretty
